name: template_secret

on:
  workflow_call:

jobs:
  pass_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Use a repo or org secret from the calling workflow.
        run: echo ${{ secrets.CLICKUP_TOKEN }}
