name: secret template

on:
  workflow_call:

jobs:
  print_debug_info:
    runs-on: ubuntu-latest
    steps:
      - name: Use a repo or org secret from the calling workflow.
        run: echo ${{ secrets.CLICKUP_TOKEN }}
